### ISSUE TITLE
Coingecko Prices

### ISSUE THREAD

**Issue by dracmic** [Haehnchen/uniswap-arbitrage-flash-swap#12]
Hey from my knowledge Coingecko prices are kinda behind do you know how to implement other possibility to get prices maybe from coinmarketcap api?

**Comment by happysammy** [comment]
Maybe from cex platform, like binance.

**Comment by mindfulme** [comment]
so it could be so that a node natively is ok but there is slow prices api

**Comment by mindfulme** [comment]
CEX is not way faster, I can do a comparison using my AWS server on NY region and requests in ms to each API endpoint as well as blockchain node to fetch prices

**Comment by mindfulme** [comment]
it takes up to 508 ms to fetch prices from coingecko and up to 200 ms using my custom blockchain node on the same server to get prices directly from each DEX router. It does not really compares as I found we have to use different sources at once and preferably several servers at once in different data centers to make sure the request is handled as fast as possible

**Comment by Haehnchen** [comment]
you dont need prices that frequently. arbitrage is happening between pairs, if there is a profit between then its calculating how much, so in this case is doesnt matter if your several percentage of.

so if there is 1 USD profit, also if you are off 20% its still 0.8 cent which higher as the transaction fee.

**Comment by dracmic** [comment]
@Haehnchen  the price of BNB is taken from coingecko as that's actually needed to calculate the tx cost which can be improved by taking from other parts like in the case of BSC from bscscan api. I think :)

**Comment by mindfulme** [comment]
nvm, use postman - browser request won't display prices. postman does
<img width="1031" alt="Screenshot 2021-07-26 at 00 22 28" src="https://user-images.githubusercontent.com/26275425/126913876-ab05e6e2-28e8-4a79-a84e-0c499cee4024.png">
