### ISSUE TITLE
Nodes (Quicknode, own AWS light node, public node)

### ISSUE THREAD

**Issue by mindfulme** [Haehnchen/uniswap-arbitrage-flash-swap#4]
So Quicknode BSC mainnet gives the best latency of less than 80ms.

Own AWS light node at lightsale with largest ($160/month instance) gives about 800 ms latency, script is running on the same server as my node.

Public BSC ws node that comes by defaut has about 500ms latency.

500 ms is not enough as all transactions fail with the error "e00" in the contract. 

Which node do you use? The region, configuration?

**Comment by Haehnchen** [comment]
simply use all all of them

- for light client you can pick every vserver < 2 USD / EUR; latency ~500ms, there is no need for bigger hardware. its still the fastest as new blocks are getting here at first
- quicknode, chainstack have lowest latency of execution < 100ms, but getting notified later for new blocks
- region: german / usa for hosting

i am never running into "e00: out of block" every transaction only takes 1-2 blocks. you can higher the "block.number + 2", but normally its too late.

**Comment by Haehnchen** [comment]
.... and feel free to remove `estimateGas` and replace it with a fixed value. this line takes normally its time ;)

```
estimateGas = await tx.estimateGas({from: admin});
```

vs

```
let estimateGas = 519540;
```

**Comment by rodolfopatane** [comment]
@Haehnchen you say "...you can higher the "block.number + 2", but normally its too late" in this code in file watcher.js at line 106 is "block.number + 2", you make modification out of this public repository? you can  share? tks

**Comment by mindfulme** [comment]
Ok, I managed to deploy my own node with 20ms in the US East region. I updated the code as well.

**Comment by happysammy** [comment]
@mindfulme do you deploy light node or full node？ AWS or other vps？

**Comment by happysammy** [comment]
> Ok, I managed to deploy my own node with 20ms in the US East region. I updated the code as well.

The bsc  push NewBlockHead timestamp is seconds, how to measure the node delay  using milliseconds?

**Comment by mindfulme** [comment]
> NewBlockHead

we measure the request time, i.e. how long it takes to fetch data from your node.

**Comment by Haehnchen** [comment]
there are 2 parts of measuring

- connect to multiple websocket providers listen for "NewBlockHead", you will notice some nodes are getting new blocks faster
- then execute the checks

so basically the calculation would be "first knowledge of the new block" + "execution time"

**Comment by happysammy** [comment]
you had better have  another measuring about the time intervals between  your NewBlockHead data's timestamp and the raw startfunction transaction is mined by validator nodes. Even if you optimize the execution time of check function < 10ms, there also are so much fails. If you look into this fail transaction, you'll find that the transaction block number often fall behind NewBlockHead data block number 1~3 blocks.
