### ISSUE TITLE
Pull updates from one of your forks 

### ISSUE THREAD

**Issue by mindfulme** [Haehnchen/uniswap-arbitrage-flash-swap#5]
This version is more up-to-date than the current repository https://github.com/defi-study/uniswap-arbitrage-flash-swap.

It is 3 commits ahead.

**Comment by StrainzAgent** [comment]
> This version is more up-to-date than the current repository https://github.com/defi-study/uniswap-arbitrage-flash-swap.
> 
> It is 3 commits ahead.

Hey, would you be able to do a step-by-step walkthrough example on a BSC testnet how to initiate the arbitrage? Or a screen record, to see exactly how it is done?  Would be awesome 🙏

**Comment by mindfulme** [comment]
> > This version is more up-to-date than the current repository https://github.com/defi-study/uniswap-arbitrage-flash-swap.
> > It is 3 commits ahead.
> 
> Hey, would you be able to do a step-by-step walkthrough example on a BSC testnet how to initiate the arbitrage? Or a screen record, to see exactly how it is done? Would be awesome 🙏

Hire me :-) $160 an hour, I can set up it for you within a very short time. My telegram @avowe
