### ISSUE TITLE
Light node error

### ISSUE THREAD

**Issue by mkroxm** [Haehnchen/uniswap-arbitrage-flash-swap#9]
Installed lite client node and its running 
Stats of node
 curl http://127.0.0.1:27147/status
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "782303c9060d46211225662fdd1dd411c638263a",
      "listen_addr": "52.197.243.252:27146",
      "network": "Binance-Chain-Tigris",
      "version": "0.32.3",
      "channels": "36402021222330380041",
      "moniker": "data-seed-0",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:27147"
      }
    },
    "sync_info": {
      "latest_block_hash": "2EA1BC407C5F9EFB18888B1FF82A96FE491B4516A320E03C5900                                               B189DF10B98C",
      "latest_app_hash": "4131F9E2D980A426FA831830688178DD3F742760083D1E72322A53                                               BF59F1CC13",
      "latest_block_height": "171146334",
      "latest_block_time": "2021-06-21T18:15:13.448450195Z",
      "catching_up": false,
      "index_height": "171146334"
    },
    "validator_info": {
      "address": "A88BAB486162E44380AA456DFA7C1DCD997985D9",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "TYgEeiyMDbt8drIPkoyAMcISvlTNVQGU6NUsL4uWEG0="
      },
      "voting_power": "0"
    }
  }

.env file updated with 
WSS_BLOCKS=tcp://127.0.0.1:27147
BSC_HTTPS=http://127.0.0.1:27147

Any idea what's missing ? please help me out !!!

**Comment by Haehnchen** [comment]
maybe websocket module not active; also "tcp://" is wrong for websocket connection. see below for defaults:

```
./geth --config ./config.toml --datadir ./node  --syncmode light --ws --http --cache 378 --light.maxpeers 50

```

extend more module if needed

```
./geth --config ./config.toml --datadir ./node  --syncmode light --ws --http --cache 378 --rpcapi 'personal,db,eth,net,web3,txpool,miner,admin,clique'
```

results to:

```
WSS_BLOCKS=ws://127.0.0.1:8546
```

**Comment by mkroxm** [comment]
Output of help on BSC light node help command as document on https://docs.binance.org/light-client.html
there's no such options for --wss or --http i think it's works with eth network any solutions for bsc light network ?

**Comment by mkroxm** [comment]
any light node setup guide available or can any one will please help me to setup my own light node or recommend any paid providers   Quicknode is not working for me all transactions fail with the error "e00" in the contract. lost around 0.25bnb any solutions please help me out

**Comment by Haehnchen** [comment]
@mkroxm 

the bash lines are directly out of the my infrastructure.

**./geth** download the binaries or compile them on or own; installing them via packages managers given you outdated stuff see and dont forgett the **./**
